default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV["PG_HOST"] %>
  port: <%= ENV["PG_PORT"] %>
  username: <%= ENV["PG_USER"] %>
  password: <%= ENV["PG_PASSWORD"] %>
#  timeout: 5000

development:
  <<: *default
  database: <%= ENV["PG_DB_DEV"] %>

test:
  <<: *default
  database: <%= ENV["PG_DB_TEST"] %>

production:
  <<: *default
  database: <%= ENV["PG_DB"] %>
